name: Suicide
version: ${project.version}
main: com.carpour.suicide.Main
authors: [ Prism3 ]
description: Simple suicide command with some cool features.
commands:
  suicide:
    description: To Suicide.
permissions:
  suicide.command:
    description: Allows to suicide.
    default: true
  suicide.bypass:
    description: Bypasses the cooldown
    default: op
  suicide.reload:
    description: Allows to reload the Plugin.
    default: op
