name: Suicide
version: ${project.version}
main: me.prism3.suicide.Main
api-version: 1.13
authors: [ Prism3 ]
description: Simple suicide command with some cool features
commands:
  suicide:
    description: To Suicide
permissions:
  suicide.command:
    description: "Suicide command"
    default: true
  suicide.bypass:
    description: "Bypasses the cooldown"
    default: op
  suicide.reload:
    description: "Reload the Plugin"
    default: op